### ISSUE TITLE
Not able to run Perl 6 notebook

### ISSUE THREAD

**Issue by sumandoc** [bduggan/p6-jupyter-kernel#14]
Hi Brian,

I have made a docker image with all dependencies (which I think is adequate) and Perl 6 kernel installed.

This is [the docker image ](https://hub.docker.com/r/sumdoc/perl-6-notebook/).

While I am able to run the Python notebook, there is not even option for Perl 6 notebook.

Relevant [question here](https://stackoverflow.com/questions/46057436/running-perl-6-kernel-in-docker).
What could I have been missing?

Best,
Suman

**Comment by sumandoc** [comment]
With [help in stackoverflow](https://stackoverflow.com/questions/46057436/running-perl-6-kernel-in-docker), I have been able to run the notebook.
I also [wrote a blog on that](https://sumdoc.wordpress.com/2017/09/06/how-to-run-perl-6-notebook/). Its super awesome. I really liked it.

But execution of the code is a bit slow. Could it be the problem in Perl 6 kernel? Just a thought.
Anyway thanks for making the Perl 6 kernel.

Best regards,
Suman

**Comment by bduggan** [comment]
Glad you got it to run and made a docker image, too.  Great blog post!  Yes, I think some work needs to be done to figure out what's going on with the CPU usage.  I'm going to close this issue since it seems that it's resolved -- i.e. the kernel does run and shows up in the menu -- but I'll continue to investigate the CPU issues.

**Comment by bduggan** [comment]
Hi @sumandoc,

This: f10feb015c89e09afcc6caa6f484bc1cb25753b4 should address the issue with 100% CPU usage.

Brian
