### ISSUE TITLE
Weird output in notebook.

### ISSUE THREAD

**Issue by sumandoc** [bduggan/p6-jupyter-kernel#28]
I have written a blog on using [Perl 6 notebook with Binder](https://sumdoc.wordpress.com/2018/01/04/using-perl-6-notebooks-in-binder/).

When trying to execute `for 1..6 {say "Hello"}` in the notebook, I get this weird output.

![ ](https://i.imgur.com/XOyJLmH.png)

While executing from terminal the output is fine:

![ ](https://i.imgur.com/O3deHl3.png)

I asked in Perl 6 IRC channel for help. Somebody suggested this:

![ ](https://i.imgur.com/25LpJXh.png)

What could be going on behind this?

**Comment by MattOates** [comment]
I reproduced this locally. If you do `print` rather than `say` it becomes a little more obvious. The output per iteration of the loop is being concatenated with the previous and then pushed onto a list that the output is rendering. Im guessing this is something to do with a run and splitting on line and storing the output? I can dig more later this eve.

**Comment by bduggan** [comment]
The reason for this is a bug in my code that wraps `$*OUT` -- basically the return value for print was accidentally the expression being printed.

But the built-in REPL kind of cheats -- if there is *any* output on stdout then it suppresses the output in the next expression, e.g.
```
