### ISSUE TITLE
Perl 6 notebooks not running in JupyterLab

### ISSUE THREAD

**Issue by sumanstats** [bduggan/p6-jupyter-kernel#40]
Hi there,

[This link](https://mybinder.org/v2/gh/sumandoc/Perl-6-notebook/master?urlpath=lab) takes me to jupyterlab environment where I can find Python and Perl 6 notebooks.

While Python notebook works without any issues, Perl 6 notebook does not execute codes in the notebook and console both.

Though the cell execution time is instantaneous in Python cells, it is still slow(though improved significantly) in Perl 6 cells.

What am I missing?

Regards,
Suman

**Comment by bduggan** [comment]
Hmm, I'm seeing inconsistent behavior trying to use the jupyterlab link above.  For the first few tries it was behaving as you describe (cells would not execute at all).  Then I selected "restart kernel" and it seemed to work fine.  Now it seems to be working fine consistently.  I also tried just using the mybinder link (without jupyterlab) and things seemed to be okay consistently.  So I wonder if there is due to some instability in the jupyterlab deployment environment (since it is still beta).  The "console" in the UI is very slow -- but when I do File->New->Terminal and then `jupyter-console --kernel=perl6`, performance seems fine.

**Comment by sumandoc** [comment]
When opening the notebook in JupyterLab, I see the Perl 6 kernel self-running without the execute command.
![capture](https://user-images.githubusercontent.com/8075886/37877651-14e86906-307e-11e8-9cad-64f2b7f1ec7b.PNG)

Without the lab environment also, even in notebook Perl 6 cells execute slower than the Python cell though much [improved than the past](https://github.com/bduggan/p6-jupyter-kernel/issues/16).

**Comment by bduggan** [comment]
Yes -- I see that too, and sometimes restarting doesn't seem to fix it.  However, when I replace "/lab" in the URL with "/tree" and then select the notebook, it works fine.  This leads me to believe that this is an issue with JupyterLab.  Maybe someone from that team has some thoughts (or ideas about how to diagnose it)?

**Comment by bduggan** [comment]
Closing this -- the raku kernel is working fine with Jupyterlab -- the link from the README to binder has an example.
